### ISSUE TITLE
FCC Focal loss  Conflict

### ISSUE THREAD

**Issue by Fyzjym** [lijian16/FCC#7]
Hi, thank you for your great and innovative work. It has inspired me a lot. 
However, I encountered a conflict between FCC and Focal loss during practical application. 
Have you ever encountered this issue? 

Here are more details: 
My task involves multiple sub-networks with corresponding losses (similar to conditional generative adversarial networks). 
When I introduced FCC or Focal loss separately in the baseline, the network could train successfully. 
However, when using both FCC and Focal loss simultaneously, the network failed to generate normal samples. 

I look forward to your response.

**Comment by lijian16** [comment]
Hi, I appreciate you pointing that out.

I haven't encountered this issue. Could you please provide more details or error messages?

**Comment by Fyzjym** [comment]
It's OK.
I solved this problem by referring to the writing method in the FCC code library.
By the way, this job is really amazing and awesome.
Thanks a lot, really.
